INSERT INTO T_PLAYER (T_PLAYER_NAME, T_PLAYER_POSITION, T_PLAYER_CLUBNAME) VALUES ('LeBron James', 'Alero', 'Los Angeles Lakers');
INSERT INTO T_PLAYER (T_PLAYER_NAME, T_PLAYER_POSITION, T_PLAYER_CLUBNAME) VALUES ('Kevin Durant', 'Ala-Pívot', 'Brooklyn Nets');
INSERT INTO T_PLAYER (T_PLAYER_NAME, T_PLAYER_POSITION, T_PLAYER_CLUBNAME) VALUES ('Stephen Curry', 'Base', 'Golden State Warriors');
INSERT INTO T_PLAYER (T_PLAYER_NAME, T_PLAYER_POSITION, T_PLAYER_CLUBNAME) VALUES ('Giannis Antetokounmpo', 'Pívot', 'Milwaukee Bucks');
INSERT INTO T_PLAYER (T_PLAYER_NAME, T_PLAYER_POSITION, T_PLAYER_CLUBNAME) VALUES ('James Harden', 'Escolta', 'Brooklyn Nets');
INSERT INTO T_PLAYER (T_PLAYER_NAME, T_PLAYER_POSITION, T_PLAYER_CLUBNAME) VALUES ('Luka Dončić', 'Base', 'Dallas Mavericks',);
INSERT INTO T_PLAYER (T_PLAYER_NAME, T_PLAYER_POSITION, T_PLAYER_CLUBNAME) VALUES ('Anthony Davis', 'Pívot', 'Los Angeles Lakers');
INSERT INTO T_PLAYER (T_PLAYER_NAME, T_PLAYER_POSITION, T_PLAYER_CLUBNAME) VALUES ('Joel Embiid', 'Pívot', 'Philadelphia 76ers');
INSERT INTO T_PLAYER (T_PLAYER_NAME, T_PLAYER_POSITION, T_PLAYER_CLUBNAME) VALUES ('Kawhi Leonard', 'Alero', 'Los Angeles Clippers');
INSERT INTO T_PLAYER (T_PLAYER_NAME, T_PLAYER_POSITION, T_PLAYER_CLUBNAME) VALUES ('Damian Lillard', 'Base', 'Portland Trail Blazers');
INSERT INTO T_PLAYER (T_PLAYER_NAME, T_PLAYER_POSITION, T_PLAYER_CLUBNAME) VALUES ('Nikola Jokić', 'Pívot', 'Denver Nuggets');
INSERT INTO T_PLAYER (T_PLAYER_NAME, T_PLAYER_POSITION, T_PLAYER_CLUBNAME) VALUES ('Devin Booker', 'Escolta', 'Phoenix Suns');
INSERT INTO T_PLAYER (T_PLAYER_NAME, T_PLAYER_POSITION, T_PLAYER_CLUBNAME) VALUES ('Chris Paul', 'Base', 'Phoenix Suns');
INSERT INTO T_PLAYER (T_PLAYER_NAME, T_PLAYER_POSITION, T_PLAYER_CLUBNAME) VALUES ('Jayson Tatum', 'Alero', 'Boston Celtics');
INSERT INTO T_PLAYER (T_PLAYER_NAME, T_PLAYER_POSITION, T_PLAYER_CLUBNAME) VALUES ('Jimmy Butler', 'Alero', 'Miami Heat');


